src/Entity/Availability.php
<?php

namespace App\Entity;

use App\Repository\AvailabilityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvailabilityRepository::class)]
class Availability
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'availabilities')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicle $vehicle = null;

    #[ORM\Column(type: 'date')]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: 'date')]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(type: 'float')]
    private ?float $price_per_day = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): static
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getPricePerDay(): ?float
    {
        return $this->price_per_day;
    }

    public function setPricePerDay(float $price_per_day): static
    {
        $this->price_per_day = $price_per_day;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\AsciiSlugger;

#[ORM\Entity(repositoryClass: VehicleRepository::class)]
class Vehicle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    /**
     * @var Collection<int, Availability>
     */
    #[ORM\OneToMany(targetEntity: Availability::class, mappedBy: 'vehicle', orphanRemoval: true)]
    private Collection $availabilities;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;


    public function __construct()
    {
        $this->availabilities = new ArrayCollection();
        $this->updateSlug();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): static
    {
        $this->brand = $brand;
        $this->updateSlug();
        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): static
    {
        $this->model = $model;
        $this->updateSlug();
        return $this;
    }

    private function updateSlug(): void
    {
        $slugger = new AsciiSlugger();
        $this->slug = strtolower($slugger->slug($this->getBrand() . '-' . $this->getModel()));
    }

    /**
     * @return Collection<int, Availability>
     */
    public function getAvailabilities(): Collection
    {
        return $this->availabilities;
    }

    public function addAvailability(Availability $availability): static
    {
        if (!$this->availabilities->contains($availability)) {
            $this->availabilities->add($availability);
            $availability->setVehicle($this);
        }

        return $this;
    }

    public function removeAvailability(Availability $availability): static
    {
        if ($this->availabilities->removeElement($availability)) {
            // set the owning side to null (unless already changed)
            if ($availability->getVehicle() === $this) {
                $availability->setVehicle(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/VehicleType.php
<?php

namespace App\Form;

use App\Entity\Vehicle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Sequentially;

class VehicleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('brand', TextType::class, [
                'constraints' => new Sequentially(
                    [
                        new NotBlank(['message' => 'Entrer une marque.']),
                        new Length(['min' => 4, 'max' => 50, 'minMessage' => 'Minimum 4 caractères.', 'maxMessage' => 'Maximum 50 caractères.']),
                        new Regex(['pattern' => '/^[A-Za-z0-9_\-\s]{3,15}$/', 'message' => 'Caractères alphanumériques uniquement.']),
                        new NotBlank(),
                    ]
                ),
                'required' => true,
            ])
            ->add('model', TextType::class, [
                'constraints' => new Sequentially(
                    [
                        new NotBlank(['message' => 'Entrer un modèle.']),
                        new Length(['min' => 4, 'max' => 50, 'minMessage' => 'Minimum 4 caractères.', 'maxMessage' => 'Maximum 50 caractères.']),
                        new Regex(['pattern' => '/^[A-Za-z0-9_\-\s]{3,15}$/', 'message' => 'Caractères alphanumériques uniquement.']),
                    ]
                ),
                'required' => true,
            ])
            ->add('availabilities', CollectionType::class, [
                'entry_type' => AvailabilityType::class,
                'allow_add' => true,
                'by_reference' => false,
            ])
            ->add('save', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicle::class,
        ]);
    }
}

src/Controller/VehiclesController.php
<?php

namespace App\Controller;

use App\Entity\Availability;
use App\Entity\Vehicle;
use App\Form\VehicleType;
use App\Repository\VehicleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Controller for managing vehicle-related operations.
 */
class VehiclesController extends AbstractController
{
    /**
     * Display a list of vehicles.
     */
    #[Route('/vehicles', name: 'vehicles.index')]
    public function index(Request $request, VehicleRepository $repository): Response
    {
        // Retrieve all vehicles from the database
        $vehicles = $repository->findAll();
        // If no vehicles are found, throw a not found exception
        if (!$vehicles) {
            throw $this->createNotFoundException('Vehicles not found');
        }
        // Render the vehicles index template with the retrieved vehicles
        return  $this->render('vehicles/index.html.twig', [
            'vehicles' => $vehicles
        ]);
    }

    /**
     * Display details of a specific vehicle.
     */
    #[Route('/vehicles/{slug}-{id}', name: 'vehicles.show', requirements: ['id' => '\d+', 'slug' => '[a-z0-9-]+'])]
    public function show(Request $request, string $slug, int $id, VehicleRepository $repository): Response
    {
        // Retrieve the vehicle with the given ID
        $vehicle = $repository->find($id);

        // If no vehicle is found, throw a not found exception
        if (!$vehicle) {
            throw $this->createNotFoundException('Vehicle not found');
        }

        // Retrieve availabilities of the vehicle
        $availabilities = $vehicle->getAvailabilities();

        // Render the vehicle details template with the retrieved data
        return $this->render("vehicles/show.html.twig", [
            'slug' => $slug,
            'id' => $id,
            'vehicle' => $vehicle,
            'availabilities' => $availabilities
        ]);
    }

    /**
     * Edit details of a vehicle.
     */
    #[Route('/vehicles/{id}/edit', name: 'vehicles.edit')]
    public function edit(Vehicle $vehicle, Request $request, EntityManagerInterface $em)
    {
        // If no vehicle is found, throw a not found exception
        if (!$vehicle) {
            throw $this->createNotFoundException('Vehicle not found');
        }

        // Create and handle the form for editing the vehicle
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            $this->addFlash('success', 'La modification a bien été prise en compte.');
            return $this->redirectToRoute('vehicles.index');
        }

        // Render the edit vehicle form
        return $this->render('vehicles/edit.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView()
        ]);
    }

    /**
     * Create a new vehicle.
     */
    #[Route('/vehicles/create', name: 'vehicles.create')]
    public function create(Request $request, EntityManagerInterface $em)
    {

        // Create a new vehicle and availability
        $vehicle = new Vehicle();
        $availability = new Availability();


        // Create and handle the form for creating the vehicle
        $vehicle->addAvailability($availability);
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($vehicle->getAvailabilities() as $availability) {
                $em->persist($availability);
            }
            $em->persist($vehicle);
            $em->flush();
            $this->addFlash('success', 'Le vehicule a bien été ajouter');
            return $this->redirectToRoute(('vehicles.index'));
        }

        // Render the create vehicle form
        return $this->render('vehicles/create.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView()
        ]);
    }

    /**
     * Delete a vehicle.
     */
    #[Route('/vehicles/{id}/delete', name: 'vehicles.delete', methods: ['DELETE'])]
    public function remove(Vehicle $vehicle, EntityManagerInterface $em)
    {
        // If no vehicle is found, throw a not found exception
        if (!$vehicle) {
            throw $this->createNotFoundException('Vehicle not found');
        }

        // Remove the vehicle from the database
        $em->remove($vehicle);
        $em->flush();

        // Add a flash message and redirect to the index page
        $this->addFlash('success', 'Le vehicule a bien été supprimer.');
        return $this->redirectToRoute('vehicles.index');
    }
}

templates/vehicles/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un vehicule
{% endblock %}


{% block body %}
	<div class="mx-auto w-full max-w-7xl  font-semibold mb-10 ">

		<p class="p-4  mt-20  text-2xl max-w-xl mx-auto bg-gray-100 text-center mb-10">

			Ajouter un vehicule
		</p>

		{% include 'partials/form.html.twig' %}

	</div>
{% endblock %}

templates/vehicles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un vehicule
{% endblock %}

{% block body %}
	<div class="mx-auto w-full max-w-7xl  font-semibold mb-10 ">

		<p class="p-4  mt-20  text-2xl max-w-xl mx-auto bg-gray-100 text-center mb-10">
			Modifier un vehicule
		</p>

		{% include 'partials/form.html.twig' %}

	</div>
{% endblock %}

templates/vehicles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Véhicules
{% endblock %}

{% block body %}
	<div class="mx-auto w-full max-w-7xl my-20  px-2 sm:px-6 lg:px-8 font-semibold">
		<p class="p-4 text-2xl max-w-xl mx-auto bg-gray-100  text-center mb-20">Liste des vehicules</p>

		<div class=" flex gap-10 items-center w-full max-w-5xl  mx-auto  pb-4">
			<p class="">
				Ajouter un véhicule:
			</p>
			<a class="text-black border border-secondary-color hover:bg-secondary-color hover:text-tertiary-color font-medium text-sm px-5 py-2.5 focus:outline-none " href={{path('vehicles.create' )}}>
				<span>Ajouter</span>
			</a>
		</div>

		<table class="w-full max-w-5xl  mx-auto">
			<thead>
				<tr class=" flex justify-between mt-10 mb-4">
					<th>
						Modifier ou supprimer un véhicule:
					</th>
				</tr>
			</thead>
			<tbody>
				{% for vehicle in vehicles %}
					<tr class=" border-b border-black  flex items-center justify-between pb-4 my-6">
						<td>
							<a class="py-2 px-3 bg-gray-100  hover:bg-gray-200 cursor-pointer" href={{path('vehicles.show',{id: vehicle.getId(),slug: vehicle.getSlug()} )}}>
								<span>{{vehicle.getBrand()}}
									-
									{{vehicle.getModel()}}</span>
							</a>
						</td>
						<td class="flex gap-4">
							<a class="text-black border border-secondary-color hover:bg-secondary-color hover:text-tertiary-color font-semibold  text-sm px-5 py-2.5 focus:outline-none" href={{path('vehicles.edit',{id: vehicle.getId()} )}}>
								<span>Modifier</span>
							</a>
							<form action={{ path('vehicles.delete', {id: vehicle.getId()} )}} method="post">

								<input type="hidden" name="_method" value="DELETE">
								<button type="submit" class="text-black border border-primary-color hover:text-tertiary-color hover:bg-primary-color font-medium text-sm px-5 py-2.5 focus:outline-none">
									<span>Suprimer</span>
								</button>
							</form>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/vehicles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ vehicle.getBrand()|capitalize }}
	-
	{{ vehicle.getModel()|capitalize }}
{% endblock %}

{% block body %}
	<div class="mx-auto w-full max-w-7xl mt-20 mb-40 px-2 sm:px-6 lg:px-8 ">

		<p class="p-4 text-2xl max-w-xl mx-auto bg-gray-100 font-semibold  text-center mb-20">{{vehicle.getBrand()| capitalize}}
			-
			{{vehicle.getModel()| capitalize}}</p>

		<div class="max-w-xl w-full mx-auto text-xl ">
			<h2 class=" mt-4 text-center font-semibold">Disponibilités</h2>
			{% for availability in availabilities %}
				<ul class="flex flex-col gap-4 mt-8 bg-tertiary-color  shadow-md p-6 ">
					<li>Disponible:
						{% if availability.isStatus == 1 %}Oui{% else %}Non
						{% endif %}
					</li>

					<li>Date de début:
						{{ availability.startDate|date('d/m/Y') }}</li>
					<li>Date de fin:
						{{ availability.endDate|date('d/m/Y') }}</li>
					<li>Prix par jour:
						{{ availability.pricePerDay }}
						€</li>
				</ul>
			{% endfor %}
		</div>
	</div>
{% endblock %}